language: python
python:
    - 2.7
matrix:
    exclude:
        - python: 2.7
    include:
        - python: 2.7
          env: TOXENV="py27"
        - python: 2.7
          env: TOXENV="py27_gevent"

install:
    - pip install --use-mirrors tox

script:
    - tox
